# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# https://blog.readthedocs.com/migrate-configuration-v2/

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/html_docs/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install
python:
  install:
    - requirements: requirements_docs.txt
    - method: pip
      path: .
      #extra_requirements:
      #  - docs
    #- method: pip
    #  path: another/package
