__author__  = 'Steven Doyle'
__email__   = 'mesheb82@gmail.com'
__desc__    = 'Nastran BDF & OP2 File reader/editor/writer/viewer'
__copyright__   = 'Copyright 2011-2012, pyNastran; %s' %(__author__)
__license__     = 'LGPLv3'
__releaseDate__ = '2012/6/6'
__releaseDate2__ = 'JUNE 6, 2012'
__version__     = '0.4.1'
__website__     = 'http://code.google.com/p/pynastran/'
